import Head from 'next/head'
import Table from '@/components/table'

const data = [
  { id: 1, name: "John", age: 25 },
  { id: 2, name: "Alice", age: 30 },
  { id: 3, name: "Bob", age: 35 },
];

const handleRowClick = (row: any) => {
  console.log("Clicked row:", row);
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Panel de control</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Panel de control</h1>
      <Table data={data} onClick={handleRowClick} />
    </>
  )
}
