import { DragMenu } from '@/components/dragMenu'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mapa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <DragMenu defaultWidth={40}>
          <h1>HOLA</h1>
        </DragMenu>
    </>
  )
}
