import Head from 'next/head'
import { useState } from 'react';
import { Building } from '@/utils/builddingsApi';
import { ModifyBoard } from './modifyBoard';
import { AdminBoard } from './adminBoard';
import styles from '@/styles/dashboard.module.sass'
export default function DashBoard() {
  const [showModifyScreen,setShowModifyScreen] = useState<boolean>(false)
  const [selectedBuilding,setSelectedBuilding] = useState<Building>()

  return (
    <>
        <Head>
            <title>Panel de control</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <AdminBoard  setSelectedBuilding={setSelectedBuilding} className={ `${styles.screen}  ${showModifyScreen?styles.hideAdmin:styles.show}` } setShowModifyScreen={()=> setShowModifyScreen(true)}/>
        <ModifyBoard building={selectedBuilding} className={ `${styles.screen} ${styles.modifyScreen} ${showModifyScreen?styles.show:styles.hideModify}` } setShowModifyScreen={()=> setShowModifyScreen(false)}/>
    </>
  ) 
}

export interface DashBoardProps extends React.HTMLAttributes<HTMLDivElement> {
    setShowModifyScreen: () => void;
    setSelectedBuilding?: (building:Building ) => void;
    building?: Building;
}